rem runs runHL.exe from all HE folders
echo off

cd HE1\run
start runHL.exe
cd ..\..\HE2\run
start runHL.exe
cd ..\..\HE3\run
start runHL.exe
cd ..\..\HE4\run
start runHL.exe
cd ..\..\HE5\run
start runHL.exe
cd ..\..\HE6\run
start runHL.exe
cd ..\..\HE7\run
start runHL.exe
cd ..\..\HE8\run
start runHL.exe
cd ..\..\HE9\run
start runHL.exe
cd ..\..\HE10\run
start runHL.exe
cd ..\..\HE11\run
start runHL.exe
cd ..\..\HE12\run
start runHL.exe
cd ..\..\HE13\run
start runHL.exe
cd ..\..\HE14\run
start runHL.exe
cd ..\..\HE15\run
start runHL.exe
cd ..\..\HE16\run
start runHL.exe
cd ..\..\HE17\run
start runHL.exe
cd ..\..\HE18\run
start runHL.exe
cd ..\..\HE19\run
start runHL.exe
cd ..\..\HE20\run
start runHL.exe